#include<iostream.h>
#define lI11 long
#define lI1l int
#define ll &
#define lI *
#define II =
void main () {char llll II'l',lIIl II'I',lIlI II'i',llII II'L',IIIl II'|',IllI
II'l',IlIl[6]II{llll,lIIl,lIlI,llII,IIIl,IllI},lI lIII II ll lIlI-2,lI IIll II
ll llll,lI llIl II ll IlIl[1],lI Illl II ll IIIl-5,lI lIll II ll IlIl [3]+2,lI
lI lllI II ll llIl+2,lI lI IIlI II ll Illl,lI lI IIII II ll IIll,lI lI IlII II
ll lIII, lI lI Il1I II ll lIll;IIll II llIl , llIl II llIl +7;IIlI ++, IIII II
Il1I,IlII--,Il1I++;double I1lI [10] ;float ll1l [5] ;lI11 double l1ll [3] II{(
lI11)ll I1lI [7] -(lI11)ll ll1l [2] ,(lI1l)ll I1lI[2]-(lI1l)ll ll1l[3],((lI1l)
ll I1lI[2])lI((lI1l)ll ll1l [3] )+(lI1l)ll I1lI[2]};for(lI1l lll1 II l1ll [1];
lll1<l1ll[0];lll1 II lll1+l1ll [2] ){llll II llll+((lI1l)ll ll1l [3] -(lI1l)ll
ll1l[4]);lIIl II lIIl +(2 lI(lI1l)ll Illl-5);llII II llII-((lI1l)ll I1lI [4]-(
lI1l)ll ll1l[2]-(lI1l)ll lIII);IllI II IllI+((lI1l)ll(lI lI lllI)+(lI1l)ll( lI
IIlI));IlIl[5]II IlIl[5]+((lI1l)ll(lI IlII)-(lI1l)ll(lI lllI))lI((lI1l)ll I1lI
[6] -(lI1l)ll I1lI[1])+(lI1l)ll IlIl[2];IlIl[3] II IlIl[3]+(lI1l)ll(lI IIII)+(
lI1l)ll IIII;IlIl[1]II IlIl[1]+((lI1l)ll ll1l[8]-(lI1l)ll ll1l[3])lI((lI1l)ll(
lI lI lllI ) - ( lI1l ) ll ( lI lI IIlI )  ) ; } cout << ll ( lI lI IlII ) ; }